name: php CI and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
      steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up PHP
        uses: shivammathur/setup-php@v2 
        with:
          php-version: '8.1' 
          tools: composer  
      - name: Install dependencies using Composer
        run: |
          composer install  # Install PHP dependencies from composer.json

      - name: Run tests
        run: |
          ./vendor/bin/phpunit --coverage-text 
