version : 0.0
os: linux
files:
    - source: /index.php
      destination: /var/www/html/

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
