version : 0.0
os: linux
files:
      source: /index.php
      destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ubuntu
      
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ubuntu
  
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ubuntu
